backend:
  name: git-gateway
  branch: develop
display_url: https://apek.or.id
media_folder: static/images # Media files will be stored in the repo under static/images
public_folder: /images # The src attribute for uploaded media will begin with /images
collections:
  - name: setting
    label: Setting
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: general
        label: General Settings
        file: content/data/settings.json
        fields:
          - name: menu
            label: Menu
            widget: list
            fields:
              - {name: text, label: Title, widget: string, required: true}
              - {name: show, label: Show, widget: boolean, default: true}
              - {name: to, label: Path, widget: string, required: true}
              - {name: icon, label: Icon, widget: icon}
              - {name: icon-alt, label: Alternative Icon, widget: icon}
              - {name: model, label: Expanded, widget: boolean}
              - {name: exact, label: Exact Path, widget: boolean}
              - name: children
                label: Children
                widget: list
                fields:
                  - {name: text, label: Title, widget: string, required: true}
                  - {name: to, label: Path, widget: string, required: true}
                  - {name: icon, label: Icon, widget: icon}
                  - {name: exact, label: Exact Path, widget: boolean}

  - name: page
    label: Page
    editor:
      preview: false
    delete: false
    files:
      - name: home
        label: Home
        file: content/pages/home.json
        fields:
          - name: carousel
            label: Carousel
            widget: list
            fields:
              - {label: Image, name: image, widget: image}

          - name: business
            label: Business Fields
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Icon, name: icon, widget: fontawesome-solid}

          - name: sponsor
            label: Sponsors
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}

      - name: Secretariat
        label: Secretariat
        file: content/pages/secretariat.json
        fields:
          - {name: title, label: Title, widget: string, required: true}
          - {name: body, label: Body, widget: markdown}
      - name: about
        label: About
        file: content/pages/about.json
        fields:
          - {name: title, label: Title, widget: string, required: true}
          - {name: body, label: Body, widget: markdown}
      - name: structure
        label: Structure
        file: content/pages/structure.json
        fields:
          - {name: title, label: Title, widget: string, required: true}
          - {name: image, label: Image, widget: image}
          - {name: body, label: Body, widget: markdown}
      - name: business
        label: Business
        file: content/pages/business.json
        fields:
          - {name: title, label: Title, widget: string, required: true}
          - {name: body, label: Body, widget: markdown}
      - name: vision-mission
        label: Vision - Mission
        file: content/pages/vision-mission.json
        fields:
          - {name: title, label: Title, widget: string, required: true}
          - {name: body, label: Body, widget: markdown}
      - name: contact
        label: Contact
        file: content/pages/contact.json
        fields:
          - {name: title, label: Title, widget: string}
          - {name: intro, label: Intro, widget: markdown}
          - {name: address, label: Address, widget: string}
          - {name: address2, label: Address 2, widget: string}
          - {name: email, label: Email, widget: list}
          - {name: phone, label: Phone, widget: list}
          - {name: fax, label: Fax, widget: list}
          - name: social
            label: Social
            widget: list
            fields:
              - {name: vendor, label: Vendor, widget: string}
              - {name: url, label: URL, widget: string}
              - {name: icon, label: Icon, widget: fontawesome-brands, default-style: 'brands', styles: ['brands']}
              - {name: color, label: Color, widget: color}

  - name: activity
    label: Activities
    label_singular: Activity
    folder: content/blog/posts/activities
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Featured Image, name: thumbnail, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}

  - name: announcement
    label: Announcements
    label_singular: Announcement
    folder: content/blog/posts/announcements
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Featured Image, name: thumbnail, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}

  - name: technology
    label: Technologies
    label_singular: Technology
    folder: content/blog/posts/technologies
    create: true
    slug: "{{slug}}"
    format: 'json'
    fields: # The fields for each document, usually in front matter
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Featured Image, name: thumbnail, widget: image, required: false}
      - {label: Body, name: body, widget: markdown}

  - name: member
    label: Member
    folder: content/members # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    fields:
      - {label: Company, name: title, widget: string}
      - {label: Address, name: address, widget: string}
      - {label: Businness, name: business, widget: list, required: false}
      - {label: Email, name: email, widget: list, required: false}
      - {label: Phone, name: phone, widget: list, required: false}
      - {label: Fax, name: fax, widget: list, required: false}
      - {label: Registered Date, name: registered, widget: date, required: false}
      - {label: Tumbnail Image, name: thumbnail, widget: image, required: false}
      - label: Products
        name: products
        widget: list
        required: false
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Description, name: description, widget: text}
      - {label: Detail, name: detail, widget: markdown, required: false}
